Merge with init_project
Chera1/task_manager pull request #1
Opened 2023-05-10 09:37 UTC by Chera1

2023-05-17 07:26 UTC, aleksandr-semenov-dbp requested changes
На этом этапе ожидается в том числе и результат startproject

2023-05-22 07:35 UTC, aleksandr-semenov-dbp requested changes

2023-05-22 07:35 UTC, aleksandr-semenov-dbp commented on Dockerfile
> +ENV PATH $PATH:/root/.poetry/bin
При установке pip-ом это не нужно

2023-05-22 07:50 UTC, Chera1 commented on Dockerfile
> +ENV PATH $PATH:/root/.poetry/bin
> При установке pip-ом это не нужно

Я прошу прощения, но я же как раз pip использую для установки poetry и дальше прописываю команды по отношению к poetry.

2023-05-29 12:53 UTC, kirill-gorshkov requested changes

2023-05-29 12:53 UTC, kirill-gorshkov commented on Dockerfile
> +ENV PATH $PATH:/root/.poetry/bin
poetry 1.4.2 устанавливается через curl в `$HOME/.local/bin`, в `$HOME/.poetry/bin` она устанавливалась, если мне не изменяет память, в версии 1.3

Эта строчка не нужна

2023-06-02 06:33 UTC, aleksandr-semenov-dbp approved these changes

2023-06-04 07:23 UTC, merged