6.6_Swagger
Chera1/task_manager pull request #15
Opened 2023-06-05 04:05 UTC by Chera1

Added the Swagger

2023-06-05 04:28 UTC, Chera1 commented
Сначала добавил Swagger, а затем прикрутил корректные проверки. Поэтому пришлось смерджить с develop после создания пул реквеста.

2023-06-06 08:03 UTC, kirill-gorshkov requested changes

2023-06-06 08:03 UTC, kirill-gorshkov commented on main/admin.py
> +    )  # Добавление поля role в отображении админки
Не оставляем комментарии в коде

2023-06-06 09:12 UTC, kirill-gorshkov requested changes

2023-06-06 09:12 UTC, kirill-gorshkov commented on task_manager/urls.py
> +    ),  # Для подключения модуля авторизации (кнопка login)
Комментариев в коде быть не должно

2023-06-06 14:03 UTC, kirill-gorshkov approved these changes

2023-06-06 15:46 UTC, merged