6.7 Tests
Chera1/task_manager pull request #17
Opened 2023-06-06 10:19 UTC by Chera1

Added base API test;
Added API tests;
Added put method in permissions;

2023-06-06 14:26 UTC, kirill-gorshkov requested changes

2023-06-06 14:26 UTC, kirill-gorshkov commented on main/permissions.py
> +        # so we'll always allow GET, HEAD, PUT or OPTIONS requests.
Комментариев быть не должно

2023-06-06 14:26 UTC, kirill-gorshkov commented on main/permissions.py
> +        ):
Зачем так сложно? Разве админу что-либо надо запрещать?

2023-06-06 14:26 UTC, kirill-gorshkov commented on main/test/base.py
> +        cls.test_tag = Tag.objects.create(**{"title": "test_tag"})
Какой тип данных мы получим при распаковке словаря?

2023-06-06 14:26 UTC, kirill-gorshkov commented on main/test/base.py
> +        assert response.status_code == HTTPStatus.FORBIDDEN, response.content
Не резонно каждый раз при вызове update() проверять, что обычный пользователь не может обновлять данные. Лучше вынести это в отдельный тип тестов, который сделает это один раз

2023-06-06 14:26 UTC, kirill-gorshkov commented on main/test/base.py
> +        self.client.force_login(self.admin)
Если при вызове каждого CRUD-метода этого класса мы логинимся под админом, может стоит вынести это в setup и сделать один раз?

2023-06-06 14:26 UTC, kirill-gorshkov commented on main/test/test_tag.py
> +        return tag
Зачем тест что-то возвращает?

2023-06-06 14:26 UTC, kirill-gorshkov commented on main/test/test_tag.py
> +    def excepted_details(entity: dict, attributes: dict):
С типизацией клево, вот бы еще типизировать тип данных, которые отдает тот или иной метод :)

2023-06-06 14:26 UTC, kirill-gorshkov commented on main/test/test_tag.py
> +        assert len(data) == 6
А откуда 6? В range всего 5 элементов

2023-06-06 14:26 UTC, kirill-gorshkov commented on main/test/test_task.py
> +        cls.task_attributes.update(
Так делать нельзя, потому что изменяются изначальные аттрибуты. Если нужна структура типа relationship_attributes, то стоит задать её в setup'е, если она динамическая, или в аттрибутах класса, если она статична

2023-06-06 14:26 UTC, kirill-gorshkov commented on main/test/test_user.py
> +    def excepted_details(entity: dict, attributes: dict):
Опечатка?

2023-06-07 02:01 UTC, Chera1 commented on main/permissions.py
> +        ):
Задача была дать разрешение на удаление только Админу. Но вы правы, я перекинул метод PUT в условие, в котором проверяется является ли пользователь персоналом.

2023-06-07 02:14 UTC, Chera1 commented on main/test/base.py
> +        cls.test_tag = Tag.objects.create(**{"title": "test_tag"})
dict

2023-06-07 03:00 UTC, Chera1 commented on main/test/base.py
> +        assert response.status_code == HTTPStatus.FORBIDDEN, response.content
Исправил также и для метода delete

2023-06-07 03:21 UTC, Chera1 commented on main/test/test_tag.py
> +        assert len(data) == 6
В setUpTestData создается тестовый тэг для тестов tasks. Тут может подскажите какие best practics применить? Чтобы взаимосвязанные сущности были доступны при инициализации(такие как tag для модели task).

2023-06-07 03:27 UTC, Chera1 commented on main/test/test_task.py
> +        cls.task_attributes.update(
Это следствие непонимания, как тестировать без заведомо созданных тестовых данных. Я изменил подход по Вашему совету и добавил обновление в setUp класса task, но не до конца понял как лучше сделать в случае с "relationship_attributes". Полностью требуется вынести из атрибута класса данный словарь с начальными данными?

2023-06-07 03:29 UTC, Chera1 commented on main/test/test_user.py
> +    def excepted_details(entity: dict, attributes: dict):
Так точно. Пишу код сам, даже в тех местах, где его можно скопировать.

2023-06-07 07:05 UTC, kirill-gorshkov commented on main/test/base.py
> +        cls.test_tag = Tag.objects.create(**{"title": "test_tag"})
То есть, `**{"title": "test_tag"} == {"title": "test_tag"}`?
А зачем тогда распаковывать?

2023-06-07 07:16 UTC, kirill-gorshkov requested changes

2023-06-07 07:16 UTC, kirill-gorshkov commented on main/permissions.py
> +        ):
ОК.
Во второй проверке можно не проверять юзера, так как если юзера нет, то и флага is_staff быть не должно

2023-06-07 07:16 UTC, kirill-gorshkov commented on main/test/test_tag.py
> +        assert len(data) == 6
Совсем не очевидно, что где-то в дереве наследования создается какой-то элемент.
Правильней всего создавать элементы только тогда, когда они нужны - во время тестов, например.

Если конкретно для этого теста нужен тег, и он нужен в каждом тесте, то стоит вынести его создание в setup.

Конкретно этот тест еще не очень хорош тем, что не совсем понятно что проверяется. 
Лучше всего сделать список этих тегов, обозначить его переменной, и ответ из self.list() сравнивать как раз с ним.

2023-06-07 07:16 UTC, kirill-gorshkov commented on main/test/base.py
> +    def not_possible_update_by_not_staff_user(self, data: dict, key: Union[int, str]):
Это лучше унести в тествьюсет юзера, или создать тесты пермишеннов и один раз там это проверить.
При добавлении новых пермишеннов эта портянка будет расти и мешать читать код базового класса.

2023-06-07 07:16 UTC, kirill-gorshkov commented on main/test/base.py
> +        Ensure we can't update an object by common user.
Комментарии не нужны :)

2023-06-07 07:36 UTC, Chera1 commented on main/test/base.py
> +        cls.test_tag = Tag.objects.create(**{"title": "test_tag"})
Потому что функция create ожидает не позиционные аргументы, а ключевые. Если мы передадим просто словарь, то вернется ошибка. Нам нужно передавать либо распакованный словарь, либо  именованные аргументы по типу title="test_tag".

2023-06-07 07:41 UTC, kgorshkoff commented on main/test/base.py
> +        cls.test_tag = Tag.objects.create(**{"title": "test_tag"})
Все верно. И читать так проще. Не надо распаковывать словари там, где это не требуется.

2023-06-07 07:43 UTC, Chera1 commented on main/test/base.py
> +        Ensure we can't update an object by common user.
Простите пожалуйста, можете объяснить в каких конкретных случаях разрешено комментировать код? В данном случае если рассматривать описание функции и иметь представление, что она будет выполнять то, что нужно, то можно убрать строчки комментариев. Но бывают же неоднозначные моменты, где комментарий может объяснить Тебе спустя долгое время, зачем Ты сделал тот или иной функционал.

2023-06-07 07:44 UTC, kgorshkoff commented on main/test/base.py
> +        Ensure we can't update an object by common user.
Мы не комментируем код вообще. Код должен быть самодокументируемым - именами методов и переменных. В данном случае из имени метода хорошо понятно, чем он занимается. Если из имени метода не понятно, чем он занимается, то стоит поискать другое имя. Буквы-то бесплатные :)

2023-06-07 07:44 UTC, Chera1 commented on main/test/base.py
> +        cls.test_tag = Tag.objects.create(**{"title": "test_tag"})
Принято

2023-06-07 07:47 UTC, Chera1 commented on main/test/base.py
> +    def not_possible_update_by_not_staff_user(self, data: dict, key: Union[int, str]):
Хорошо. А в тех случаях, когда пермишены будут отличаться между вьюсетами? У меня уже есть тесты пермишенов и там проверяется только модель task

2023-06-07 07:49 UTC, Chera1 commented on main/test/base.py
> +        Ensure we can't update an object by common user.
Согласен) Но Вы же мне пометили на докстринг, а не комментарий. Докстринг, то за что?)) Или пока он без определений ретернов и аргументов - это простой комментарий?)

2023-06-07 07:49 UTC, kirill-gorshkov commented on main/test/base.py
> +    def not_possible_update_by_not_staff_user(self, data: dict, key: Union[int, str]):
Правильней всего будет создать отдельные тесты для пермишенов и проверять их один раз там. Проверенные пермишены будут точно работать для все вьюсетов, на которые их назначат

2023-06-07 07:51 UTC, Chera1 commented on main/test/base.py
> +    def not_possible_update_by_not_staff_user(self, data: dict, key: Union[int, str]):
Хорошо, принял.

2023-06-07 07:56 UTC, kirill-gorshkov commented on main/test/base.py
> +        Ensure we can't update an object by common user.
Докстринги мы тоже не пишем, они врать могут. Забыл кто-то поправить, написал неправильно - все, привет, сиди разбирайся. 

А код так не умеет - не работает, значит не работает, и поддерживать меньше. 
Ретёрны и аргументы прекрасно заменяются типизацией, которая еще и линтерами проверяется.

Если хочется - пишите на здоровье, больше докстринги трогать не буду :)

2023-06-07 07:59 UTC, Chera1 commented on main/test/base.py
> +        Ensure we can't update an object by common user.
Учту на будущее, спасибо!

2023-06-08 12:45 UTC, kirill-gorshkov approved these changes

2023-06-08 12:45 UTC, kirill-gorshkov commented on main/test/test_permissions.py
>  class AccountTests(APITestCase):
Это только не AccountTest, а PermissionTestViewSet

2023-06-09 08:03 UTC, merged