Merging with tag and task model
Chera1/task_manager pull request #5
Opened 2023-05-11 06:15 UTC by Chera1

Created tag and task models;
Added and used a black tool.

2023-05-19 07:08 UTC, aleksandr-semenov-dbp requested changes
Здесь должны быть миграции

2023-05-19 07:14 UTC, Chera1 commented
> Здесь должны быть миграции

Имеется ввиду миграционные файлы?  0001_.... ? 
Я думал такие файлы отправляются в репозиторий.

2023-05-22 06:56 UTC, aleksandr-semenov-dbp requested changes
Должны быть миграции

2023-05-29 12:32 UTC, kirill-gorshkov approved these changes

2023-06-04 07:25 UTC, merged