Merging with tests
Chera1/task_manager pull request #7
Opened 2023-05-12 07:52 UTC by Chera1

Added default null value to author and performer fields;
Added tests for models.

2023-05-22 06:59 UTC, aleksandr-semenov-dbp requested changes

2023-05-22 06:59 UTC, aleksandr-semenov-dbp commented on main/test/test_admin.py
> +            # print(f'{app_label}_{model_name}_{action}')
комментированый код и отладочные принты в репозиторий не отправляем

2023-05-29 12:48 UTC, kirill-gorshkov requested changes

2023-05-29 12:48 UTC, kirill-gorshkov commented on main/models/task.py
> +        null=True
Миграции?

2023-06-01 15:13 UTC, aleksandr-semenov-dbp approved these changes

2023-06-04 07:26 UTC, merged